import type { DocumentData, Message } from '../../types';
import type { GoldenScenario } from './types';

const existingZcrmDocument: DocumentData = {
  businessAnalysis: {
    content: [
      '# ZCRM110 Toplu Statü Güncelleme',
      '',
      '## Amaç ve Kapsam',
      'SAP CRM üzerinde seçilen müşteri kayıtlarının statüsü toplu olarak güncellenir.',
      'Legacy Support kapsamı ve mevcut dokümanlar, açıkça düzenlenmedikçe değişmeden kalır.',
      '',
      '## İş Kuralları',
      '| Kural | Açıklama |',
      '|---|---|',
      '| BR-01 | Kullanıcı yalnızca yetkili olduğu kayıtları günceller. |',
      '| BR-02 | Hatalı kayıtlar diğer başarılı kayıtları geri aldırmaz. |',
      '',
      '## Açık Konular',
      'Toplu işlem üst limiti iş birimi tarafından onaylanmalıdır.',
    ].join('\n'),
    status: 'DRAFT',
    flags: [],
  },
  review: {
    content: [
      '# Review',
      '[AÇIK KONU] Toplu işlem üst limiti.',
      '[VARSAYIM] Legacy Support dokümanları değişmeyecek.',
    ].join('\n'),
    status: 'NEEDS_REVISION',
    flags: [],
  },
};

const discoveryHistory: Message[] = [
  {
    id: 'history-ai-1',
    role: 'model',
    text: 'Kritik kararları netleştirelim.',
    questions: [{
      id: 'q1',
      text: 'Ana hedef nedir?',
      options: ['Operasyonel hız', 'Kalite', 'Uyum'],
    }],
  },
  {
    id: 'history-user-1',
    role: 'user',
    text: '**Soru 1:** Ana hedef nedir?\nCevap: Operasyonel hız; ilk sürüm yalnızca SAP CRM toplu statü güncellemesi.',
  },
];

export const goldenScenarios: GoldenScenario[] = [
  {
    id: 'CONV-001',
    title: 'Saf selamlama dokümana dokunmaz',
    category: 'conversation',
    userMessage: 'Merhaba',
    subIntent: 'small_talk',
    expectedAction: 'answer_only',
  },
  {
    id: 'CONV-002',
    title: 'Selamlama düzeltmesi sohbet olarak kalır',
    category: 'conversation',
    userMessage: 'Ben sadece selam dedim',
    subIntent: 'small_talk',
    expectedAction: 'answer_only',
  },
  {
    id: 'CONV-003',
    title: 'Ürün kullanımı sorusu sohbet yanıtıdır',
    category: 'conversation',
    userMessage: 'Bu uygulamayı nasıl kullanırım?',
    subIntent: 'help_usage',
    expectedAction: 'answer_only',
  },
  {
    id: 'CONV-004',
    title: 'Bağlamsal sonraki adım sorusu doküman üretmez',
    category: 'conversation',
    userMessage: 'Şimdi sırada ne var?',
    subIntent: 'ask_how_to',
    expectedAction: 'answer_only',
  },
  {
    id: 'CONV-005',
    title: 'Yapılandırılmış iş problemi önce anlaşılır ve doküman üretilmez',
    category: 'conversation',
    userMessage: 'Problem: Abonelik iptal ve iade talepleri farklı kanallarda izlenemiyor. Mevcut durum: Çağrı merkezi ve operasyon ekipleri ayrı listeler kullanıyor. Hedef durum: Talepleri tek iş listesinde izlemek ve karar geçmişini kaydetmek.',
    subIntent: 'start_new_requirement',
    expectedAction: 'answer_only',
  },
  {
    id: 'DISC-001',
    title: 'Seyrek SAP CRM AI fikri önce keşif ister',
    category: 'discovery',
    userMessage: 'SAP CRM AI satış botu projesi',
    subIntent: 'generate_business_analysis',
    expectedAction: 'ask_questions',
  },
  {
    id: 'DISC-002',
    title: 'Seyrek hassas entegrasyon resmi kaynak ve keşif ister',
    category: 'discovery',
    userMessage: 'SAP CRM KKB Findeks API entegrasyonu kavramsal dokümanı hazırla',
    subIntent: 'generate_business_analysis',
    expectedAction: 'ask_questions',
  },
  {
    id: 'DISC-003',
    title: 'Kısa genel BA doküman talebi kritik sorulara yönelir',
    category: 'discovery',
    userMessage: 'İade süreci için BA analiz dokümanı hazırla',
    subIntent: 'generate_business_analysis',
    expectedAction: 'ask_questions',
  },
  {
    id: 'DISC-004',
    title: 'Eksik seçili metnin mevcut seçim aksiyonu dondurulur',
    category: 'discovery',
    userMessage: 'Seçtiğim metni daha kurumsal yap',
    subIntent: 'make_selected_text_corporate',
    classificationOverrides: {
      documentImpact: 'updates_selected_text',
      targetSection: 'businessAnalysis',
    },
    expectedAction: 'update_selected_text',
  },
  {
    id: 'DISC-005',
    title: 'Açıklama zorunluluğunun mevcut normalizasyon sonucu dondurulur',
    category: 'discovery',
    userMessage: 'Bu gereksinimde karar sahibi belli değil, netleştirelim',
    subIntent: 'identify_missing_information',
    classificationOverrides: {
      requiresClarification: true,
      clarificationQuestions: ['Karar sahibi kim?'],
    },
    expectedAction: 'answer_only',
  },
  {
    id: 'DISC-006',
    title: 'Yanıtlanan keşif turu üretime geçer',
    category: 'discovery',
    userMessage: '**Soru 1:** Ana hedef nedir?\nCevap: Operasyonel hız; bu bilgilerle dokümanı hazırla.',
    subIntent: 'answer_clarification',
    messages: discoveryHistory,
    expectedAction: 'draft_document',
  },
  {
    id: 'DRAFT-001',
    title: 'Varsayım onaylı kavramsal taslak üretilir',
    category: 'drafting',
    userMessage: 'SAP CRM AI satış botu için kavramsal tasarım dokümanı hazırla, varsayımlarla ilerle',
    subIntent: 'generate_business_analysis',
    expectedAction: 'draft_document',
  },
  {
    id: 'DRAFT-002',
    title: 'Detaylı iade platformunda mevcut ek soru davranışı dondurulur',
    category: 'drafting',
    userMessage: [
      'Proje Adı: Abonelik İptal ve İade Operasyon Platformu',
      'Roller: Müşteri temsilcisi, operasyon lideri, finans onaycısı',
      'Süreç 1 - İptal talebinin alınması',
      'Süreç 2 - Hak ediş ve iade kontrolü',
      'Süreç 3 - Finans onayı ve ödeme',
      'Sistemler: Müşteri Portalı, ERP, Ödeme Servisi',
      'KPI: İade tamamlanma süresi ve hata oranı',
      'BA analiz dokümanını hazırla.',
    ].join('\n'),
    subIntent: 'generate_business_analysis',
    expectedAction: 'ask_questions',
  },
  {
    id: 'DRAFT-003',
    title: 'Teknik analizde mevcut kaynak sorusu davranışı dondurulur',
    category: 'drafting',
    userMessage: 'Sipariş servisi için teknik analiz hazırla; bileşen, veri modeli, hata yönetimi ve loglama dahil olsun',
    subIntent: 'generate_technical_analysis',
    classificationOverrides: {
      documentImpact: 'updates_document',
      shouldRunBaAgentLoop: true,
      baAgentFocus: 'technical_analysis',
    },
    expectedAction: 'ask_questions',
  },
  {
    id: 'DRAFT-004',
    title: 'Test senaryosunda mevcut kaynak blokajı dondurulur',
    category: 'drafting',
    userMessage: 'Toplu statü güncelleme için pozitif, negatif ve yetki test senaryolarını hazırla',
    subIntent: 'generate_test_cases',
    classificationOverrides: {
      documentImpact: 'updates_document',
      shouldRunBaAgentLoop: true,
      baAgentFocus: 'test',
    },
    expectedAction: 'ask_questions',
  },
  {
    id: 'DRAFT-005',
    title: 'API kontratı kaynak hassasiyetini işaretler',
    category: 'drafting',
    userMessage: 'Müşteri izin servisi için API kontratı hazırla, varsayımlarla ilerle',
    subIntent: 'generate_api_contract',
    classificationOverrides: {
      documentImpact: 'updates_document',
      shouldRunBaAgentLoop: true,
      baAgentFocus: 'technical_analysis',
    },
    expectedAction: 'draft_document',
  },
  {
    id: 'DRAFT-006',
    title: 'Süreç akışı BA dokümanı içinde üretilir',
    category: 'drafting',
    userMessage: 'İade onay süreci için Mermaid akışını hazırla, mevcut bilgilerle ilerle',
    subIntent: 'generate_mermaid',
    classificationOverrides: {
      documentImpact: 'updates_document',
      shouldRunBaAgentLoop: true,
      baAgentFocus: 'flow',
    },
    expectedAction: 'draft_document',
  },
  {
    id: 'REV-001',
    title: 'Mevcut dokümana kapsam maddesi eklenir',
    category: 'revision',
    userMessage: 'Kapsama başarısız kayıtların ayrı hata listesinde gösterilmesini ekle',
    subIntent: 'append_to_section',
    document: existingZcrmDocument,
    expectedAction: 'revise_document',
  },
  {
    id: 'REV-002',
    title: 'Canlı testteki doküman koruma maddesi revizyon sayılır',
    category: 'revision',
    userMessage: 'Mevcut dokümanlar açıkça düzenlenmedikçe etkilenmesin maddesini ekle',
    subIntent: 'capture_constraint',
    classificationOverrides: {
      documentImpact: 'updates_document',
      targetSection: 'businessAnalysis',
    },
    document: existingZcrmDocument,
    workspaceTitle: 'SAP CRM Toplu Statü Analizi Retest',
    expectedAction: 'revise_document',
  },
  {
    id: 'REV-003',
    title: 'Açık onarım talebi repair moduna girer',
    category: 'revision',
    userMessage: 'Word formatına düzelt ve eksikleri tamamla',
    subIntent: 'revise_section',
    document: existingZcrmDocument,
    expectedAction: 'repair_document',
  },
  {
    id: 'REV-004',
    title: 'Risk incelemesi dokümanı gizlice değiştirmez',
    category: 'revision',
    userMessage: 'Bu dokümandaki riskleri ve tutarsızlıkları bul',
    subIntent: 'find_risks',
    document: existingZcrmDocument,
    expectedAction: 'validate_document',
  },
  {
    id: 'REV-005',
    title: 'Yüksek riskli içerik silme önizleme ister',
    category: 'revision',
    userMessage: 'İş kuralları bölümünü tamamen kaldır',
    subIntent: 'remove_content',
    classificationOverrides: {
      documentImpact: 'requires_user_confirmation',
      operation: 'remove_content',
      riskLevel: 'high',
      requiresPreview: true,
    },
    document: existingZcrmDocument,
    expectedAction: 'preview_change',
  },
  {
    id: 'REV-006',
    title: 'Seçili metin mevcutsa yalnız seçimi günceller',
    category: 'revision',
    userMessage: 'Seçili metni daha kurumsal yap',
    subIntent: 'make_selected_text_corporate',
    classificationOverrides: {
      documentImpact: 'updates_selected_text',
      targetSection: 'businessAnalysis',
    },
    document: existingZcrmDocument,
    selectedText: 'Hatalı kayıtları ayrıca göster.',
    expectedAction: 'update_selected_text',
  },
  {
    id: 'RESEARCH-001',
    title: 'Açık araştırma isteği dokümandan önce araştırır',
    category: 'research_review',
    userMessage: 'Toplu güncelleme UX best practice kaynaklarını araştır',
    subIntent: 'research_best_practice',
    classificationOverrides: {
      requiresResearch: true,
      researchType: 'web',
    },
    expectedAction: 'research_first',
  },
  {
    id: 'RESEARCH-002',
    title: 'Hassas API taslağı resmi kaynak zorunluluğu taşır',
    category: 'research_review',
    userMessage: 'KKB Findeks API entegrasyonu için kavramsal doküman hazırla, varsayımlarla ilerle',
    subIntent: 'generate_business_analysis',
    expectedAction: 'draft_document',
  },
  {
    id: 'RESEARCH-003',
    title: 'Kalite puanlama salt okunur doğrulama aksiyonudur',
    category: 'research_review',
    userMessage: 'Dokümanı kalite, testlenebilirlik ve açık konular açısından puanla',
    subIntent: 'score_document',
    document: existingZcrmDocument,
    expectedAction: 'validate_document',
  },
  {
    id: 'SYS-001',
    title: 'Proje kararı hafıza aksiyonuna yönlenir',
    category: 'system_workflow',
    userMessage: 'Karar olarak kaydet: toplu işlem limiti 500 kayıt',
    subIntent: 'save_decision',
    expectedAction: 'memory_action',
  },
  {
    id: 'SYS-002',
    title: 'Dışa aktarmanın mevcut revizyon yönlendirmesi dondurulur',
    category: 'system_workflow',
    userMessage: 'Dokümanı dışa aktar',
    subIntent: 'export_document',
    document: existingZcrmDocument,
    expectedAction: 'revise_document',
  },
  {
    id: 'SYS-003',
    title: 'Zero Touch kapalıyken sistem mesajı döner',
    category: 'system_workflow',
    userMessage: '/ekip bu analizi tüm ajanlarla otomatik tamamla',
    subIntent: 'zero_touch_requested',
    zeroTouchEnabled: false,
    expectedAction: 'system_message',
  },
  {
    id: 'SYS-004',
    title: 'Bekleyen işlem yokken çıplak uygula güvenli biçimde durur',
    category: 'system_workflow',
    userMessage: 'uygula',
    subIntent: 'answer_clarification',
    pendingOperationLookupPerformed: true,
    pendingOperationId: null,
    expectedAction: 'pending_operation_missing',
  },
  {
    id: 'SYS-005',
    title: 'Bekleyen işlem varsa iptal komutu güvenli iptale yönlenir',
    category: 'system_workflow',
    userMessage: 'iptal',
    subIntent: 'answer_clarification',
    pendingOperationLookupPerformed: true,
    pendingOperationId: 'pending-sprint0-001',
    expectedAction: 'cancel_pending_change',
  },
];

export const goldenDocuments = {
  existingZcrmDocument,
};
